### PR TITLE
Removing unused commands

### PR DESCRIPTION
**Pull request by raulmarcosl**
Reviewing the different commands of `cbot` I have seen a lot of commands that we don't use, and that haven't been modified in two years. A lot of them don't work because are related to old projects.

My proposal is to delete them, leaving only the commands we use: `hi`, `qa`, `decide`, `karma`, `ping` and `potty_mouth`. Also I'd leave `rspec` because although is not working maybe we want to use it in the future.

What do you think @ciscou?

### CODE REVIEW

**Comment by raulmarcosl** [comment]
@arctarus Why the label? 🤔

**Comment by arctarus** [comment]
@raulmarcosl I didn't add the label. I think it was a change added by github automagically :smile:

**Comment by dpzaba** [comment]
:ok: but you are going to miss one of the most relevant gifs at cabify

**Comment by MarkVillacampa** [comment]
sublime!

**Comment by amuino** [comment]
@dpzaba what are you doing here? 🤣

**Comment by patriciagao** [comment]
Don't remove _alex, _blamed, _zaba commands please.

**Comment by raulmarcosl** [comment]
@patriciagao Ok, I des-removed them 🙂 Are you ok with deleting the other commands?

**Pull request merged**
